//
//  LocalizedKey.swift
//  DocLive
//
//  Created by WFH on 15/04/20.
//  Copyright © 2020 Codiant. All rights reserved.
//

import Foundation

enum LocalizedKey: String { 
    
    // MARK: - Network Layer
    case baseUrlNotConfigured   = "BASE_URL_NOT_CONFIGURED"
    case jsonEncodingFailError  = "JSON_ENCODE_FAIL"
    case badRequestError        = "BAD_REQUEST_ERROR"
    case urlMissingError        = "URL_MISSING_ERROR"
    case invalidEncodingType    = "INVALID_ENCODING_ERROR"
    case networkReqFailed       = "NETWORK_REQ_FAILED"
    case noDataError            = "NO_DATA_ERROR"
    case unableToDecodeError    = "UNABLE_TO_DECODE_ERROR"
    case parameterNil           = "PARAMETER_NIL"
    case parameterEncodeFail    = "PARAMETER_ENCODE_FAIL"
    case urlNil                 = "URL_NIL"
    case checkNetworkConnection = "CHECK_NETWORK_CONNECTION"
    case sessionExpired         = "SESSION_EXPIRED"
    case lastSessionExpired     = "LAST_SESSION_EXPIRED"
    case apiFailed              = "API_FAILED"
    case networkTitle           = "NETWORK_TITLE"
    case tryAgian               = "TRY_AGIAN"
    case goToSetting            = "GO_TO_SETTING"
    
    // MARK: - Titles
    case alert      = "ALERT"
    case ok         = "OK"
    case cancel     = "CANCEL"
    case logout     = "LOGOUT"
    
    // MARK: - Labels, Titles
    case forgotPassword         = "FORGOT_PASSWORD"
    case signup                 = "SIGNUP"
    case useEmailInstead        = "USE_EMAIL_INSTEAD"
    case useMobileInstead       = "USE_MOBILE_INSTEAD"
    case privacyPolicy          = "PRIVACY_POLICY"
    case termsCondition         = "TERMS_CONDITION"
    case howItWorks             = "HOW_IT_WORK"
    case resendCode             = "RESEND_CODE"
    case update                 = "UPDATE"
    case next                   = "NEXT"
    case confirm                = "CONFIRM"
    case mobileNumber           = "MOBILE_NUMBER"
    case or                     = "OR"
    case backToLogin            = "BACK_TO_LOGIN"
    case signupAsPrimaryUser    = "SIGNUP_AS_PRIMARY_USER"
    case signupAsSecondUser    = "SIGNUP_AS_SECOND_USER"
 
    case signupAsMerchant       = "SIGNUP_AS_MERCHANT"
    case searchYourCountry      = "SEARCH_YOUR_COUNTRY"
    case pickCountry            = "PICK_COUNTRY"
    case selectCountry          = "SELECT_COUNTRY"
 
    case changeMobileNumber     = "CHANGE_MOBILE_NUMBER"
    case enterNewMobileNumber   = "ENTER_NEW_MOBILE_NUMBER"
    case sendCode               = "SEND_CODE"
    case actionTC               = "ACTION_TC"
    case actionPP               = "ACTION_PP"
    case actionCS               = "ACTION_CS"
    case enterNameMobileNumber  = "ENTER_NAME_MOBILE_NUMBER"
    case contact                = "CONTACT"
    case block                  = "BLOCK"
    case pleaseAuthenticate     = "PLEASE_AUTHENTICATE"
    case contacts               = "CONTACTS"
    case paymentRequestType     = "PAYMENT_REQUEST_TYPE"
    case paymentRequest         = "PAYMENT_REQUEST"
    case viewAll                = "VIEW_ALL"
    case received               = "RECEIVED"
    case recentTransactions     = "RECENT_TRANSACTIONS"
    case contactSaveStatus      = "CONTACT_SAVE_STATUS"
    case isNotOnMonay           = "IS_NOT_ON_MONAY"
    case enterNameOrMobileNumber = "ENTER_NAME_OR_MOBILE_NUMBER"
    case contactsOnMonay        = "CONTACTS_ON_MONAY"
    case allContacts            = "ALL_CONTACTS"
    case cardAmericanExpress    = "CARD_AMERICAN_EXPRESS"
    case savedCards             = "SAVED_CARDS"
    case failed                 = "FAILED"
    case sendMoneyFailed        = "SEND_MONEY_FAILED"
    case requestMoneyFailed     = "REQUEST_MONEY_FAILED"
    case addMoneyFailed         = "ADD_MONEY_FAILED"
    case withdrawMoneyFailed    = "WITHDRAW_MONEY_FAILED"
    case moneySentSuccessfully  = "MONEY_SENT_SUCCESSFULLY"
    case requestForMoneySuccessfully = "REQUEST_FOR_MONEY_SUCCESSFULLY"
    case moneyAddedSuccessfully      = "MONEY_ADDED_SUCCESSFULLY"
    case withdrawMoneySuccessfully   = "WITHDRAW_MONEY_SUCCESSFULLY"
    case transactionID               = "TRANSACTION_ID"
    case to                          = "TO"
    case myRequest                   = "MY_REQUEST"
    case restFilter                  = "REST_FILTER"
    case fromDate                    = "FROM_DATE"
    case toDate                      = "TO_DATE"
    case transfer                    = "TRANSFER"
    case added                       = "ADDED"
    case withdraw                    = "WITHDRAW"
    case deposite                    = "DEPOSITE"
    case transactionType             = "TRANSACTION_TYPE"
    case clearFilter                 = "CLEAR_FILTER"
    case secureText                  = "SECURE_TEXT"
    case inProgress                  = "IN_PROGRESS"
    case completed                   = "COMPLETED"
    case rejected                     = "REJECTED"
    case resetPin                     = "RESET_PIN"
    case resetMonayPin                = "RESET_MONAY_PIN"
    case backToSecurity               = "BACK_TO_SECURITY"
    case enterNewPin                  = "ENTER_NEW_PIN"
    case confirmNewPin                = "CONFIRM_NEW_PIN"
    case forgotPin                    = "FORGOT_PIN"
    case add                          = "ADD"
    case kycPending                   = "KEY_PENDING"
    case kycVerified                  = "KEY_VERIFIED"
    case kycRejected                  = "KEY_REJECTED"
    case custID                       = "CUST_ID"
    case qrCode                       = "QR_CODE"
    case verifyEmail                  = "VERIFY_EMAIL"
    case changeNumber                 = "CHANGE_NUMBER"
    case changeEmail                  = "CHANGE_EMAIL"
    case pngImage                     = "PNG_IMAGE"
    case image                        = "IMAGE"
    case transactions                 = "TRANSACTIONS"
    case yes                          = "YES"
    case no                           = "NO" 
    case paid                         = "PAID"
    case decline                      = "DECLINE"
    case declined                     = "DECLINED"
    case receipt                      = "RECEIPT"
    case changePin                    = "CHANGE_PIN"
    case withdrawal                   = "WITHDRAWAL"
    case paidTo                       = "PAID_TO"
    case ending                       = "ENDING"
    case uploaded                     = "UPLOADED"
    case approved                     = "APPROVED"
    case selectPictureIdentificationDoc = "SELECT_PICTURE_IDENTIFICATION_DOC"
    case passport                       = "PASSPORT"
    case driverLicense                  = "DRIVER_LICENSE"
    case nationalID                     = "NATIONAL_ID"
    case selectProofOfAddress           = "SELECT_PROOF_OF_ADDRESS"
    case utilityBill                    = "UTILITY_BILL"
    case bankStatement                  = "BANK_STATEMENT"
    case rentalContract                 = "RENTAL_CONTRACT"
    case postMarkedMail                 = "POST_MARKED_MAIL"
    case chooseMediaSource              = "CHOOSE_MEDIA_SOURCE"
    case camera                         = "CAMERA"
    case gallery                        = "GALLERY"
    case document                       = "DOCUMENT"
    case pending                        = "PENDING"
    case pdfImage                       = "PDF_IMAGE"
    case pdf                            = "PDF"
    case jpeg                           = "JPEG"
    case jpg                            = "JPG"
    case png                            = "PNG"
    case settings                       = "SETTINGS"
    case supports                       = "SUPPORTS"
    case accountNumber                  = "ACCOUNT_NUMBER"
    case selectBank                     = "SELECT_BANK"
    case blockContacts                  = "BLOCK_CONTACTS"
    case issueAddMoney                  = "ISSEU_ADD_MONEY"
    case issueSendMoney                 = "ISSEU_SEND_MONEY"
    case issueRequestMoney              = "ISSEU_REQUEST_MONEY"
    case failedTransactions             = "FAILED_TRANSACTIONS"
    case needhelpInAccountSettings      = "NEED_HELP_IN_ACCOUNT_SETTINGS"
    case kycSupport                     = "KYC_SUPPORT"
    case reportFraudActivity            = "REPORT_FRAUD_ACTIVITY"
    case others                         = "OTHERS"
    case login                          = "LOGIN"
    case versionUpdate                  = "VERSION_UPDATE"
    case allowCamera                    = "ALLOW_CAMERA"
    case dismiss                        = "DISMISS"
    case position                       = "POSITION"
    case scan                           = "SCAN"
    case errorDomain                    = "YOUR_ERROR_DOMAIN_VALUE"
    case spam                           = "SPAM"
    case identifiedSpam                 = "IDENTIFIED_SPAM"
    case digit                          = "DIGITS"
    case countryCode                    = "COUNTRY_CODE"
    case gifName                        = "LOADER_SPIN"
    case noDataImage                    = "NO_DATA_IMAGE"
    case notResultFoundImage            = "NO_RESULT_FOUND_IMAGE"
    case noInternetImage                = "NO_INTERNET_IMAGE"
    case searchAgain                    = "SEARCH_AGAIN"
    case contactSupport                 = "CONTACT_SUPPORT"
    // MARK: - Error Alert
    case messageInvalidTokenExpiration  = "INVALID_TOKEN_EXPIRATION"
    case messageJWTTokenExpired         = "JWT_TOKEN_EXPIRED"
    case messageUnableAccessCamera      = "UNABLE_CAMERA_ACCESS"
    case messageEnableCameraPermission  = "CAMERA_PERMISSION_ENABLE"
    case messageUnableAccessGallery     = "UNABLE_GALLERY_ACCESS"
    case messageEnableGalleryPermission = "GALLERY_PERMISSION_ENABLE"
    case messageNoDataAvailable         = "NO_DATA_AVAILABLE"
    case accountInactive                = "ACCOUNT_INACTIVE_VALUE"
    case blockedUser                    = "BLOCKED_USER"
    case phoneNotFound                  = "PHONE_NOT_FOUND_VALUE"
    case transactionLimitExhausted      = "TRANSACTION_LIMIT_EXHAUSTED_VALUE"
    case messageErrorLoadingData        = "ERROR_LOADING_DATE"
    case messageFailedInitData          = "FAILED_INIT_DATA"
  
    // MARK: - Validation Alert
    case messageEnterFirstName        = "ENTER_FIRST_NAME"
    case messageEnterLastName         = "ENTER_LAST_NAME"
    case messageEnterEmail            = "ENTER_EMAIL"
    case messageEnterCorrectEmail     = "ENTER_CORRECT_EMAIL"
    case messageEnterPassword         = "ENTER_PASSWORD"
    case messageEnterValidPassword    = "ENTER_VALID_PASSWORD"
    case messageEnterConfirmPassword  = "ENTER_CONFIRM_PASSWORD"
    case messagePasswordsNotMatch     = "PASSWORD_NOT_MATCH"
    case messageEnterMobileNumber     = "ENTER_MOBILE_NUMBER"
    case messageMobileNumberValidLength   = "MOBILE_NUMBER_VALID_LENGTH"
    case messageEnterCurrentPassword      = "ENTER_CURRENT_PASSWORD"
    case messageEnterValidCurrentPassword = "ENTER_VALID_CURRENT_PASSWORD"
    case messageCameraAccessRequired      = "CAMERA_ACCESS_REQUIRED"
    case meaasgeAllowCameraAccess         = "ALLOW_CAMERA_ACCESS"
    case canNotFind                       = "CAN_NOT_FIND"
    
  case messageEnterCompanyName            = "ENTER_COMPANY_NAME"
  case messageEnterTaxID                  = "ENTER_TAX_ID"
  case messageTaxIDLength                 = "TAX_ID_VALID_LENGTH"
  case messageEnterChamberCommerce        = "ENTER_CHAMBER_COMMERCE"
  case messageChamberCommerceValidLength  = "CHAMBER_COMMERCE_VALID_LENGTH"
  case messageAgreeTNC                    = "AGREE_TNC_PRIVACY_POLICY"
  case messageEmailAlreadyExist           = "EMAIL_ALREADY_EXIST"
  case messageAccoountDisableByAdmin      = "ACCOUNT_DISABLE_BY_ADMIN"
  
  case messgeEnterCodeSentOnEmail         = "ENTER_CODE_SENT_ON_EMAIL"
  case messgeEnterCodeSentOnMobile        = "ENTER_CODE_SENT_ON_MOBILE"
  case messgeEnterCodeSentOnMobileForVerification = "ENTER_CODE_SENT_ON_MOBILE_FOR_VERIFICATION" // swiftlint:disable:this identifier_name
  case messageEnterCodeSentOnEmailForVerification = "ENTER_CODE_SENT_ON_EMAIL_FOR_VERIFICATION" // swiftlint:disable:this identifier_name
  case messgeEnterVerificationCode        = "ENTER_VERIFICATION_CODE"
  case messgeVerificationCodeValidLength  = "VERIFICATION_CODE_VALID_LENGTH"
  
  case messgeEnterRegisteredMobileNumber  = "ENTER_REGISTERED_MOBILE_NUMBER"
  case messgeEnterRegisteredEmail         = "ENTER_REGISTERED_EMAIL"
  case messageEnterNewPassword            = "ENTER_NEW_PASSWORD"
  case messagePasswordValidation          = "PASSWORD_VALIDATION"
  case messageEnterConfirmNewPassword     = "ENTER_CONFIRM_NEW_PASSWORD"
  case messagePasswordShouldSame          = "PASSWORD_SHOULD_SAME"
  case messageCurrentPasswordSouldSame    = "CURRENT_PASSWORD_SHOULD_SAME"
  case grandUseContactPermission          = "GRANT_USE_CONTACT_PERMISSION"
  case appProtactsDataToAvoidUnauthorizeAccess = "APP_PROTECTS_DATA"
  case messageEnterValidCVV               = "ENTER_VALID_CVV"
  case messageEnterAmount                 = "ENTER_AMOUNT"
  case amountGreaterThanOne               = "AMOUNT_GREATER_ONE_VALIDATION"
  case messageInsufficientFundInWallet    = "INSUFFICIENT_FUND_IN_WALLET"
  case messageCardExpired                 = "CARD_EXPIRED"
  case sureDeclineRequest                 = "SURE_DECLINE_REQUEST"
  case notFound                           = "NOT_FOUND"
  case tryEnteringMobileNumber            = "TRY_ENTERING_MOBILE_NUMBER"
  case selectFromDate                     = "SELECT_FROM_DATE"
  case invalidCode                        = "INVALID_CODE"
  case scanFailed                         = "SCAN_FAILED"
  case messageEnterFourDigitPin           = "ENTER_FOUR_DIGIT_PIN"
  case messageEnterPin                    = "ENTER_PIN"
  case messageEnterValidPin               = "ENTER_VALID_PIN"
  case messageEnterConfirmPin             = "ENTER_CONFIRM_PIN"
  case enterValidConfirmPin               = "ENTER_VALID_CONFIRM_PIN"
  case messagePinConfirmPinShouldSame     = "PIN_CONFIRM_PIN_SHOULD_SAME"
  case messageEnterOldPin                 = "ENTER_OLD_PIN"
  case messageEnterValidOldPin            = "ENTER_VALID_OLD_PIN"
  case messageEnterNewPin                 = "MESSAGE_ENTER_NEW_PIN"
  case messageEnterValidNewPin            = "ENTER_VALID_NEW_PIN"
  case messageEnterConfirmNewPin          = "ENTER_CONFIRM_NEW_PIN"
  case messageEnterValidConfirmNewPin     = "ENTER_VALID_CONFIRM_NEW_PIN"
  case messageNewPinConfirmPinSouldSame   = "NEW_PIN_SHOULD_SAME"
  case messageFileSizeValidation          = "FILE_SIZE_VALIDATION"
  case messageUpdateSaveNewEmail          = "UPDATE_SAVE_NEW_EMAIL"
  case messageSelectExpiryDate            = "SELECT_EXPIRY_DATE"
  case messageEnterValidExpiryDate        = "ENTER_VALID_EXPIRY_DATE"
  case messageEnterValidExpiryYear        = "ENTER_VALID_EXPIRY_YEAR"
  case messageEnterValidExpiryMonth       = "ENTER_VALID_EXPIRY_MONTH"
  case messageEnterCVV                    = "ENTER_CVV"
  case messageCVVInfo                     = "CVV_INFO"
  case messageEnterName                   = "ENTER_NAME"
  case messageEnterCardNumber             = "ENTER_CARD_NUMBER"
  case messageEnterValidCardNumber        = "ENTER_VALID_CARD_NUMBER"
  case messageEnterAccountHolderName      = "ENTER_ACCOUNT_HOLDER_NAME"
  case messageEnterBankName               = "ENTER_BANK_NAME"
  case messageEnterBankAccountNumber      = "ENTER_BANK_ACCOUNT_NUMBER"
  case messageEnterRoutingNumber          = "ENTER_ROUTING_NUMBER"
  case messageEnterValidRoutingNumber     = "ENTER_VALID_ROUTING_NUMBER"
  case messageEnterIFSCCode               = "ENTER_IFSC_CODE"
  case messageSecureAccessMonay           = "SECURE_ACCESS_MONAY"
  case messageEnableTouchAndFaceId        = "ENABLE_TOUCH_AND_FACE_ID"
  case messageSelectIdentificationType    = "SELECT_IDENTIFICATION_TYPE"
  case messageSelectIdentificationDocument = "SELECT_IDENTIFICATION_DOCUMENT"
  case messageSelectAddressProofType       = "SELECT_ADDRESS_PROOF_TYPE"
  case messageSelectAddressProofDocument   = "SELECT_ADDRESS_PROOF_DOCUMENT"
  case messageDocumentFileMustType         = "DOCUMENT_FILE_MUST_TYPE"
  case messageAddBank                      = "ADD_BANK"
  case messageSelectBank                   = "MESSAGE_SELECT_BANK"
  case messageInsufficientFunds            = "INSUFFICIENT_FUNDS"
  case messageEnterMessage                 = "ENTER_MESSAGE"
  case messageSureLogout                   = "SURE_LOGOUT"
  case msaageNewUpdateAvailable            = "NEW_UPDATES_AVAILABLE"
  case failedToDequeue                     = "FAILED_TO_DEQUEUE"
  case messageCheckReuseIdentifier         = "CHECK_REUSE_IDENTIFIER"
  case messageRegisterCellBeforehand       = "REGISTER_CELL_BEFOREHAND"
  case messageNotResultFound               = "NO_RESULT_FOUND"
  case messageNoRelevantDataAvailable      = "NO_RELEVANT_DATA_AVAILABLE"
  case messageNoInternetConnection         = "NO_INTERNET_CONNECTION"
  case checkInternetConnetion              = "CHECK_INTERNET_CONNECTION"
  case messageCanNotRequestMoneyYourself   = "CAN_NOT_REQUEST_MONEY_YOURSELF"
  case messageCanNotSendMoneyYourself      = "CAN_NOT_SEND_MONEY_YOURSELF"
  
  case messageSelectIdentificationFrontDocument = "SELECT_IDENTIFICATION_FRONT_DOCUMENT"
  case messageSelectAddressProofFrontDocument   = "SELECT_ADDRESS_PROOF_FRONT_DOCUMENT"
  case messageSelectIdentificationBackDocument = "SELECT_IDENTIFICATION_BACK_DOCUMENT"
  case messageSelectAddressProofBackDocument   = "SELECT_ADDRESS_PROOF_BACK_DOCUMENT"
  case messageEnterRefillAmount           = "ENTER_REFILL_AMOUNT"
  
  // Values
  case headerWidth = "HEADER_WIDTH"
  case width       = "WIDTH"
  case headerView  = "HEADER_VIEW"
  
    var value: String {
        return NSLocalizedString(rawValue, comment: "Localized value not found for key: \(rawValue)")
    }
}
