disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- multiple_closures_with_trailing_closure
- inclusive_language

identifier_name:
  min_length:
    warning: 2

excluded:
- Carthage
- Pods
- Monay/Misc
- Monay/APIManager/Core
- Monay/Model/Misc

line_length: 250  # default 120 characters

function_body_length: 70 # default 40 lines

function_parameter_count: 7 # default 5

file_length: 1000 # default 400

type_body_length: 400

cyclomatic_complexity: 50
