[features]
seeds = false
skip-lint = false

[programs.localnet]
monay_invoice_system = "INVo1CEfT0KeN5M0NaY2025ENT3RPR1SE"

[programs.devnet]
monay_invoice_system = "INVo1CEfT0KeN5M0NaY2025ENT3RPR1SE"

[programs.mainnet]
monay_invoice_system = "INVo1CEfT0KeN5M0NaY2025ENT3RPR1SE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# Configuration for invoice system
[workspace]
members = ["programs/invoice-nft"]

# Dependencies for compressed NFTs
[dependencies]
mpl-bubblegum = "0.7.0"
spl-account-compression = "0.2.0"
spl-noop = "0.1.3"

# Test configuration
[test]
startup_wait = 5000

# Deployment configuration
[deploy]
# Maximum program size (2MB)
max_size = 2097152

# Optimization settings
[optimizer]
runs = 200
enabled = true

# Network endpoints
[cluster.devnet]
url = "https://api.devnet.solana.com"

[cluster.mainnet]
url = "https://api.mainnet-beta.solana.com"

[cluster.localnet]
url = "http://127.0.0.1:8899"